export type CityOption = {
  name: string
  country: string
  countryCode: string
  timezone: string
}

export const CITIES: CityOption[] = [
  { name: 'Bagerhat', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Bandarban', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Barguna', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Barishal', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Bhola', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Bogura', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Brahmanbaria', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Chandpur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Chattogram', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Chuadanga', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: "Cox's Bazar", country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Cumilla', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Dhaka', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Dinajpur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Faridpur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Feni', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Gaibandha', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Gazipur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Gopalganj', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Habiganj', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Jamalpur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Jashore', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Jhalokathi', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Jhenaidah', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Joypurhat', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Khagrachhari', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Khulna', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Kishoreganj', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Kurigram', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Kushtia', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Lakshmipur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Lalmonirhat', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Madaripur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Magura', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Manikganj', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Meherpur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Moulvibazar', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Munshiganj', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Mymensingh', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Naogaon', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Narail', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Narayanganj', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Narsingdi', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Natore', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Chapai Nawabganj', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Netrokona', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Nilphamari', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Noakhali', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Pabna', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Panchagarh', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Patuakhali', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Pirojpur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Rajbari', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Rajshahi', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Rangamati', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Rangpur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Satkhira', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Shariatpur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Sherpur', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Sirajganj', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Sunamganj', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Sylhet', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Tangail', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },
  { name: 'Thakurgaon', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' }
]
